private const val kotlinVersion = "1.8.0"
private const val coreKtxVersion = "1.9.0"
private const val appCompatVersion = "1.6.1"
private const val constraintLayoutVersion = "2.1.4"
private const val legacyVersion = "1.0.0"
private const val recyclerViewVersion = "1.3.0"
private const val googleMaterialVersion = "1.8.0"
private const val splashscreenVersion = "1.0.1"

object Main {
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    const val coreKtx = "androidx.core:core-ktx:$coreKtxVersion"
    const val appCompat = "androidx.appcompat:appcompat:$appCompatVersion"
    const val activityKtx = "androidx.activity:activity-ktx:$appCompatVersion"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"
    const val legacy = "androidx.legacy:legacy-support-v4:$legacyVersion"
    const val recyclerView = "androidx.recyclerview:recyclerview:$recyclerViewVersion"
    const val splashScreen = "androidx.core:core-splashscreen:$splashscreenVersion"
    const val googleMaterial = "com.google.android.material:material:$googleMaterialVersion"
}