private const val okhttpVersion = "4.10.0"
private const val retrofit2Version = "2.9.0"
private const val moshiVersion = "1.14.0"
private const val koinVersion = "1.8.0"
private const val hiltVersion = "2.44"
private const val sqlChipperVersion = "4.4.2"
private const val glideVersion = "4.14.2"
private const val timberVersion = "5.0.1"
private const val hiltNavCompose = "1.0.0"
private const val sharedElementVersion = "0.1.0-SNAPSHOT"
private const val libPhoneNumberVersion = "8.2.0"

object Misc {
    const val okhttp = "com.squareup.okhttp3:okhttp:$okhttpVersion"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:$okhttpVersion"
    const val retrofit = "com.squareup.retrofit2:retrofit:$retrofit2Version"
    const val converterMoshi = "com.squareup.retrofit2:converter-moshi:$retrofit2Version"
    const val moshi = "com.squareup.moshi:moshi:$moshiVersion"
    const val moshiKotlin = "com.squareup.moshi:moshi-kotlin:$moshiVersion"
    const val koinCore = "org.koin:koin-core:$koinVersion"
    const val koinAndroid = "org.koin:koin-android:$koinVersion"
    const val koinAndroidScope = "org.koin:koin-androidx-scope:$koinVersion"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:$koinVersion"
    const val koinFragment = "org.koin:koin-androidx-fragment:$koinVersion"
    const val hiltAndroid = "com.google.dagger:hilt-android:$hiltVersion"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:$hiltVersion"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:$hiltNavCompose"
    const val sqlcipher = "net.zetetic:android-database-sqlcipher:$sqlChipperVersion"
    const val coilCompose = "io.coil-kt:coil-compose:2.4.0"
    const val circularImageView = "com.mikhaellopez:circularimageview:4.3.0"
    const val prettyTime = "org.ocpsoft.prettytime:prettytime:4.0.4.Final"
    const val glide = "com.github.bumptech.glide:glide:$glideVersion"
    const val timber = "com.jakewharton.timber:timber:$timberVersion"
    const val sharedElement = "com.mxalbert.sharedelements:shared-elements:$sharedElementVersion"
    const val libPhoneNumber = "com.googlecode.libphonenumber:libphonenumber:$libPhoneNumberVersion"
}